95 refactor unit tests
VegeWaterDynamics/motrainer pull request #100
Opened 2023-12-06 13:21 UTC by rogerkuou

fix #95

2023-12-06 13:39 UTC, rogerkuou commented
Hi @SarahAlidoost, when you have time, could you please also review this one for me? I improved the unit tests to increase the coverage and speed.

2023-12-06 14:53 UTC, SarahAlidoost commented on motrainer/jackknife.py
> +            metedata['lon'] = float(self.gpi_data['lon'].iloc[0])
I like that you implemented the check for coordinates. This part of the code is also changed in #97 with respects to the coordinate names that should be `latitude` and `longitude`. can you please merge the `generalization` into your branch and resolve the merge conflicts?

2023-12-06 14:54 UTC, SarahAlidoost commented on motrainer/util.py
>  os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'  # Force tensorflow debug logging off
This file is also changed in #97, can you please merge the generalization into your branch? There, I changed the value of `os.environ['TF_CPP_MIN_LOG_LEVEL']` from '3' to '2'. :smile:

2023-12-06 15:01 UTC, SarahAlidoost commented on tests/test_dnn.py
> +)
```suggestion
EXPECTED_DIMS = {
    "learning_rate",
    "num_dense_layers",
    "num_input_nodes",
    "num_dense_nodes",
    "activation",
    "batch_size",
}
```

2023-12-06 15:37 UTC, SarahAlidoost requested changes
@rogerkuou nice work :+1:  please see my comments. One question: You mentioned that this pull request improves the speed of the tests. I am just curious about how you measured it. how much improvement in the speed is reached? :thinking:

2023-12-08 11:36 UTC, rogerkuou commented
Hi @SarahAlidoost, thanks for the review!
I applied most of your comments. Apart from the one on checking `best_loss` and `history`, see my comments. Could you please give another look?

2023-12-11 13:30 UTC, SarahAlidoost commented
> Hi @SarahAlidoost, thanks for the review! I applied most of your comments. Apart from the one on checking `best_loss` and `history`, see my comments. Could you please give another look?

Thanks for addressing the comments, feel free to merge :+1:

2023-12-11 14:55 UTC, merged